"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import utils
import numpy as np
import matplotlib.pyplot as plt


def factors(x):
    if x == 1:
        return np.array([1])
    c = np.arange(1, x/2 + 1, dtype=int)
    return np.append(c[np.where(np.mod(x, c) == 0)[0]], x)


def solve(N):
    # all2s_lb = np.prod(utils.primes(int(np.ceil(np.log2(N + 1)))))
    # unique_lb = 2**int(np.ceil(np.log2(N + 1)))
    # a = int(np.ceil(np.max(np.roots(np.array([1, 1, -2*N])))))
    # x = (a*(a + 1))//2
    x = 1
    a = 1
    p = np.array([1])
    while True:
        # print("{}: {}".format(x, utils.divisors(x)))
        p = np.append(p, utils.factor_count(x))
        if p[-1] > N:
            break
        a += 1
        x += a
    # plt.plot(p)

    return x



def scratch(N):
    a = int(np.ceil(np.max(np.roots(np.array([1, 1, -2*N])))))
    x = (a*(a + 1))//2
    f = np.array([], int)
    while True:
        if utils.factor_count(x) <= N:
            break

        a += 1
        x += a
    return x

# utils.divisors(10)
# scratch(500)
# print(solve(5))
# assert(solve(5) == 28)
# print(solve(300))
print(solve(500))

